openapi: '3.0.2'
info:
  title: Customer API
  version: '1.0'
  contact:
    name: Accenture
    email: contact@example.com
    url: http://example.com
servers:
  - url: https://api.server.test/v1

tags:
  - name: Customer API
    description: Create and Fetch Customer

paths:
  /customer:
    post:
      description: Create Customer
      summary: Create customer for given request.
      tags:
        - "Customer API"
      operationId: createCustomer
      requestBody:
        description: Request Body for Create Customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
  /customer/{id}:
    get:
      description: Get Customer
      summary: Get Customer for a given id
      tags:
        - "Customer API"
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          description: Fetch customer with the ID
          required: true
          example: 12345
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
        '400':
          description: Bad Request
        '404':
          description: Customer Not Found


components:
  schemas:
    Customer:
      description: This is a customer schema
      type: object
      required:
        - "customerId"
      properties:
        customerId:
          type: string
          description: ID of the customer
          example: 12345
          minLength: 5
          maxLength: 8
      
        customerName:
          type: string
          description: Name of the customer (firstname/lastname)
          example: CloudNative Trainee
        customerAddress:
          type: string
          description: Address of the customer
          example: Atlanta, GA
        officeCode:
          type: integer
          description: Customer's Office officeCode
          example: 5555
