openapi: '3.0.2'
info:
  title: Customer API
  version: '1.0'
  contact:
    name: Accenture 
    email: contact@example.com
    url: http://example.com
servers:
  - url: https://api.server.test/v1

tags: 
  - name: Customer API
    description: Create and fetch customers 

paths:
  /customer:
    post:
      description: Create Customer
      summary: Create customer for given request
      tags:
        - "Customer API"
      operationId: createCustomer
      requestBody: 
        description: Create customer schema
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content: 
            application/json: 
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
  /customer/{id}: 
    get:
      description: Get Customer
      summary: Get customer for given id
      tags:
        - "Customer API"
      operationId: getCustomer
      parameters: 
        - name: id
          in: path
          description: Get customer
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: OK
          content: 
            application/json: 
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
        '400':
          description: Invalid Request 
        '404': 
          description: Customer not found 

components: 
  schemas:
    Customer:
      description: Customer schema
      type: object
      required: 
        - 'customerId'
      properties:
        customerId:
          type: string
          description: Id of the customer 
          example: 123456
          minLength: 5
          maxLength: 8
        customerName: 
          type: string 
          description: Name of the customer (firstname/lastname)
          example: Mr. Test
        customerAddress: 
          type: string 
          description: Address
          example: City, St
        officeCode:
          type: integer
          description: Office office
          example: 714


