openapi: '3.0.2'
info:
  title: Customer Api
  version: '1.0'
  contact:
    name: Accenture
    email: test@example.com
    url: https://example.com
servers:
  - url: https://api.server.test/v1

tags:
  - name: Customer API
    description: Create and get Customer
  
paths:
  /customer:
    post:
      description: create customer
      summary: create customer for given request
      tags:
        - "Customer API"
      operationId: createCustomer
      requestBody:
        description: Request body schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Error Ocurred
  /customer/{id}:
    get:
      operationId: getCustomer
      description: get customer details
      parameters:
        - name: id
          in: path
          description: fetch customer
          required: true
          schema:
            type: string
      tags:
        - "Customer API"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad Request




components:
  schemas:
    Customer:
      description: This is customer schema
      type: object
      required:
        - "customerId"
      properties:
        customerId:
          type: string
          description: customer ID
          example: 12345
          minLength: 5
          maxLength: 8
        customerName:
          type: string
          description: customer name
          example: sruthi
        customerAddr:
          type: string
          description: customer Address
          example: 123 test road nj